// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_REQUEST     JobType = 1
	JobType_JOB_TYPE_RESPONSE    JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_REQUEST",
		2: "JOB_TYPE_RESPONSE",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_REQUEST":     1,
		"JOB_TYPE_RESPONSE":    2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

type IngestStatus int32

const (
	IngestStatus_INGEST_STATUS_UNSPECIFIED IngestStatus = 0
	IngestStatus_INGEST_STATUS_ACCEPTED    IngestStatus = 1
	IngestStatus_INGEST_STATUS_REJECTED    IngestStatus = 2
)

// Enum value maps for IngestStatus.
var (
	IngestStatus_name = map[int32]string{
		0: "INGEST_STATUS_UNSPECIFIED",
		1: "INGEST_STATUS_ACCEPTED",
		2: "INGEST_STATUS_REJECTED",
	}
	IngestStatus_value = map[string]int32{
		"INGEST_STATUS_UNSPECIFIED": 0,
		"INGEST_STATUS_ACCEPTED":    1,
		"INGEST_STATUS_REJECTED":    2,
	}
)

func (x IngestStatus) Enum() *IngestStatus {
	p := new(IngestStatus)
	*p = x
	return p
}

func (x IngestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_proto_enumTypes[1].Descriptor()
}

func (IngestStatus) Type() protoreflect.EnumType {
	return &file_ingest_proto_enumTypes[1]
}

func (x IngestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestStatus.Descriptor instead.
func (IngestStatus) EnumDescriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=apiobserver.ingest.v1.JobType" json:"type,omitempty"`
	Request       *Request               `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Response      *Response              `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *Job) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Job) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Request) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ContentLength int64                    `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Metadata      *Metadata                `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Response) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *Response) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        IngestStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=apiobserver.ingest.v1.IngestStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *IngestAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *IngestAck) GetStatus() IngestStatus {
	if x != nil {
		return x.Status
	}
	return IngestStatus_INGEST_STATUS_UNSPECIFIED
}

func (x *IngestAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestAck) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\x15apiobserver.ingest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.apiobserver.ingest.v1.JobTypeR\x04type\x128\n" +
	"\arequest\x18\x03 \x01(\v2\x1e.apiobserver.ingest.v1.RequestR\arequest\x12;\n" +
	"\bresponse\x18\x04 \x01(\v2\x1f.apiobserver.ingest.v1.ResponseR\bresponse\"{\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd3\x02\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.apiobserver.ingest.v1.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12;\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1f.apiobserver.ingest.v1.MetadataR\bmetadata\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.apiobserver.ingest.v1.HeaderValuesR\x05value:\x028\x01\"\xcc\x02\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.apiobserver.ingest.v1.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength\x12;\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1f.apiobserver.ingest.v1.MetadataR\bmetadata\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.apiobserver.ingest.v1.HeaderValuesR\x05value:\x028\x01\"\x97\x01\n" +
	"\tIngestAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.apiobserver.ingest.v1.IngestStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable*P\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JOB_TYPE_REQUEST\x10\x01\x12\x15\n" +
	"\x11JOB_TYPE_RESPONSE\x10\x02*e\n" +
	"\fIngestStatus\x12\x1d\n" +
	"\x19INGEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INGEST_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16INGEST_STATUS_REJECTED\x10\x022[\n" +
	"\rIngestService\x12J\n" +
	"\x06Ingest\x12\x1a.apiobserver.ingest.v1.Job\x1a .apiobserver.ingest.v1.IngestAck(\x010\x01B'Z%api-observer/proto/ingest/v1;ingestv1b\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ingest_proto_goTypes = []any{
	(JobType)(0),                  // 0: apiobserver.ingest.v1.JobType
	(IngestStatus)(0),             // 1: apiobserver.ingest.v1.IngestStatus
	(*Job)(nil),                   // 2: apiobserver.ingest.v1.Job
	(*Metadata)(nil),              // 3: apiobserver.ingest.v1.Metadata
	(*HeaderValues)(nil),          // 4: apiobserver.ingest.v1.HeaderValues
	(*Request)(nil),               // 5: apiobserver.ingest.v1.Request
	(*Response)(nil),              // 6: apiobserver.ingest.v1.Response
	(*IngestAck)(nil),             // 7: apiobserver.ingest.v1.IngestAck
	nil,                           // 8: apiobserver.ingest.v1.Request.HeadersEntry
	nil,                           // 9: apiobserver.ingest.v1.Response.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_ingest_proto_depIdxs = []int32{
	0,  // 0: apiobserver.ingest.v1.Job.type:type_name -> apiobserver.ingest.v1.JobType
	5,  // 1: apiobserver.ingest.v1.Job.request:type_name -> apiobserver.ingest.v1.Request
	6,  // 2: apiobserver.ingest.v1.Job.response:type_name -> apiobserver.ingest.v1.Response
	10, // 3: apiobserver.ingest.v1.Metadata.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 4: apiobserver.ingest.v1.Request.headers:type_name -> apiobserver.ingest.v1.Request.HeadersEntry
	3,  // 5: apiobserver.ingest.v1.Request.metadata:type_name -> apiobserver.ingest.v1.Metadata
	9,  // 6: apiobserver.ingest.v1.Response.headers:type_name -> apiobserver.ingest.v1.Response.HeadersEntry
	3,  // 7: apiobserver.ingest.v1.Response.metadata:type_name -> apiobserver.ingest.v1.Metadata
	1,  // 8: apiobserver.ingest.v1.IngestAck.status:type_name -> apiobserver.ingest.v1.IngestStatus
	4,  // 9: apiobserver.ingest.v1.Request.HeadersEntry.value:type_name -> apiobserver.ingest.v1.HeaderValues
	4,  // 10: apiobserver.ingest.v1.Response.HeadersEntry.value:type_name -> apiobserver.ingest.v1.HeaderValues
	2,  // 11: apiobserver.ingest.v1.IngestService.Ingest:input_type -> apiobserver.ingest.v1.Job
	7,  // 12: apiobserver.ingest.v1.IngestService.Ingest:output_type -> apiobserver.ingest.v1.IngestAck
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		EnumInfos:         file_ingest_proto_enumTypes,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
