// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"sidebar\"><div class=\"sidebar-header\"><div class=\"sidebar-title\">API Observer</div><button id=\"theme-toggle\" class=\"theme-toggle\" type=\"button\" aria-label=\"Switch color theme\" title=\"Switch color theme\"><span class=\"theme-icon-light\" aria-hidden=\"true\">☀</span> <span class=\"theme-icon-dark\" aria-hidden=\"true\">☾</span></button> <label for=\"sidebar-toggle\" class=\"sidebar-close\" aria-label=\"Close navigation\">&times;</label></div><nav class=\"sidebar-nav\" aria-label=\"Primary navigation\"><a href=\"/log-explorer\">Log Explorer</a> <a href=\"/rules\">Rules</a></nav></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SidebarThemeToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\t\t(function () {\n\t\t\tconst button = document.getElementById(\"theme-toggle\");\n\n\t\t\tif (!button) {\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\tfunction updateLabel() {\n\t\t\t\tconst currentTheme = document.documentElement.dataset.theme;\n\n\t\t\t\tbutton.setAttribute(\n\t\t\t\t\t\"aria-label\",\n\t\t\t\t\tcurrentTheme === \"dark\"\n\t\t\t\t\t\t? \"Switch to light mode\"\n\t\t\t\t\t\t: \"Switch to dark mode\",\n\t\t\t\t);\n\t\t\t}\n\n\t\t\tbutton.addEventListener(\"click\", function () {\n\t\t\t\tconst currentTheme = document.documentElement.dataset.theme;\n\t\t\t\tconst nextTheme = currentTheme === \"dark\" ? \"light\" : \"dark\";\n\n\t\t\t\tdocument.documentElement.dataset.theme = nextTheme;\n\t\t\t\tlocalStorage.setItem(\"theme\", nextTheme);\n\n\t\t\t\tupdateLabel();\n\t\t\t});\n\n\t\t\tupdateLabel();\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
